In [53]:
import numpy as np
import pandas as pd

from sklearn.datasets import load_wine
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split, KFold
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

In [54]:
info = load_wine()
info

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]], shape=(178, 13)),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [55]:
print(info.DESCR)

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

:Number of Instances: 178
:Number of Attributes: 13 numeric, predictive attributes and the class
:Attribute Information:
    - Alcohol
    - Malic acid
    - Ash
    - Alcalinity of ash
    - Magnesium
    - Total phenols
    - Flavanoids
    - Nonflavanoid phenols
    - Proanthocyanins
    - Color intensity
    - Hue
    - OD280/OD315 of diluted wines
    - Proline
    - class:
        - class_0
        - class_1
        - class_2

:Summary Statistics:

============================= ==== ===== ======= =====
                                Min   Max   Mean     SD
============================= ==== ===== ======= =====
Alcohol:                      11.0  14.8    13.0   0.8
Malic Acid:                   0.74  5.80    2.34  1.12
Ash:                          1.36  3.23    2.36  0.27
Alcalinity of Ash:            10.6  30.0    19.5   3.3
Magnesium:                    70.0 162.0    99.7  14.3

In [56]:
x = pd.DataFrame(info.data, columns=info.feature_names)
x

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  
0                            3.92   1065.0  
1                            3.40   1050.0  
2                            3.17   1185.0  
3                            3.45   1480.0  
4                            2.93    735.0  
..                            ...      ...  
173                          1.74    740.0  
174                          1.56    750.0  
175                          1.56    835.0  
176                          1.62    840.0  
177                          1.60    560.0  

[178 rows x 13 columns]

In [57]:
y = info.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [58]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
dtypes: fl

In [59]:
x[["alcohol", "malic_acid", "ash", "alcalinity_of_ash", "magnesium", "total_phenols", "flavanoids", "nonflavanoid_phenols", "proanthocyanins", "color_intensity", "hue", "od280/od315_of_diluted_wines", "proline"]] = x[["alcohol", "malic_acid", "ash", "alcalinity_of_ash", "magnesium", "total_phenols", "flavanoids", "nonflavanoid_phenols", "proanthocyanins", "color_intensity", "hue", "od280/od315_of_diluted_wines", "proline"]].astype("float16")

In [60]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   alcohol                       178 non-null    float16
 1   malic_acid                    178 non-null    float16
 2   ash                           178 non-null    float16
 3   alcalinity_of_ash             178 non-null    float16
 4   magnesium                     178 non-null    float16
 5   total_phenols                 178 non-null    float16
 6   flavanoids                    178 non-null    float16
 7   nonflavanoid_phenols          178 non-null    float16
 8   proanthocyanins               178 non-null    float16
 9   color_intensity               178 non-null    float16
 10  hue                           178 non-null    float16
 11  od280/od315_of_diluted_wines  178 non-null    float16
 12  proline                       178 non-null    float16
dtypes: fl

In [65]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25,  random_state=42)

In [66]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((133, 13), (133,), (45, 13), (45,))

In [68]:
scaler = MinMaxScaler()

x_train_sc = pd.DataFrame(scaler.fit_transform(x_train), columns=x_train.columns, index=x_train.index)
x_test_sc = pd.DataFrame(scaler.transform(x_test), columns=x_test.columns, index=x_test.index)


In [69]:
np.unique(y, return_counts=True)

(array([0, 1, 2]), array([59, 71, 48]))

In [71]:
model = LogisticRegression(solver="newton-cg")
model.fit(x_train, y_train)

LogisticRegression(solver='newton-cg')

In [73]:
pred_train = model.predict(x_train)

In [74]:
pred_test = model.predict(x_test)

In [75]:
accuracy_score(y_train, pred_train), accuracy_score(y_test, pred_test)

(0.9924812030075187, 1.0)

### Without Sklearn 

In [76]:
x_train_b = np.concatenate((np.ones((x_train_sc.shape[0], 1)), x_train_sc), axis=1)
x_test_b = np.concatenate((np.ones((x_test_sc.shape[0], 1)), x_test_sc), axis=1)

In [77]:
beta = np.linalg.inv(x_train_b.T @ x_train_b) @ x_train_b.T @ y_train

In [78]:
y_pred = x_test_b @ beta
y_pred

array([ 0.14913557,  0.27796342,  1.50160005,  0.23510875,  0.93130221,
        0.12541923,  0.94734413,  1.94248332,  0.48867389,  1.41567466,
        0.15625645,  1.97738158,  0.40548116,  1.33861261,  0.14205862,
        1.05945232,  1.22870671,  1.0578269 ,  0.12475753,  0.93755518,
       -0.33744033,  0.55663313,  1.13036653,  2.05423697,  2.22861646,
        2.051096  ,  1.01343511,  0.74309698,  1.08295945,  0.50945354,
        0.16611797,  1.05479   ,  1.61189083,  0.08135931,  0.02841609,
       -0.23801659,  2.20404285,  2.0592835 ,  0.52158617,  2.20769449,
        0.2348726 ,  1.07138699,  0.74492795,  0.95404334,  1.57214675])

In [85]:
y_pred_log = 1 / (1 + np.exp(-y_pred))
y_pred_log

array([0.53721494, 0.56904686, 0.817813  , 0.55850793, 0.7173394 ,
       0.53131377, 0.72058075, 0.87462471, 0.61979398, 0.80465944,
       0.53898482, 0.87840176, 0.60000385, 0.79226169, 0.53545505,
       0.74258587, 0.77359214, 0.74227504, 0.53114899, 0.71860555,
       0.41643139, 0.63567315, 0.75590653, 0.88637504, 0.90279001,
       0.88605832, 0.73369187, 0.67767271, 0.74705362, 0.62467836,
       0.54143425, 0.74169365, 0.83367374, 0.52032862, 0.50710355,
       0.44077519, 0.90061197, 0.88688231, 0.62751859, 0.90093835,
       0.5584497 , 0.74486059, 0.67807252, 0.7219276 , 0.82808943])

In [86]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [90]:
-np.mean(y_test*np.log(y_pred_log) + (1 - y_test) * np.log(1 - y_pred_log))

np.float64(-0.07796153699889911)